version: "3.8"
services:
  mongodb:
      image : mongo
      container_name: mongodb
      restart: always
      build:
        context: .
        dockerfile: mongodb-data/Dockerfile    
      ports:
      - 27017:27017
      restart: unless-stopped
  web-api:
    build: .
    container_name: payment-button-api
    ports: 
      - "8081:80"      
    depends_on: 
      - mongodb   