trigger:
- master

variables:
- template: ../cicd-variables.yaml  # Template reference

resources:
  repositories:
  - repository: commonPipelinesRepo
    type: git
    name: devops-assets/common-pipelines

stages:
- template: net-core-app/Build.payment-button-api.yaml@commonPipelinesRepo
  parameters:
      path-to-project: $(path-to-project) # path to solution or project that will be used in the build and restore tasks
      build-configuration:  $(build-configuration)
      dotnet-version:  $(dotnet-version)
      nuget-path:  $(nuget-path)
      pool-name:  $(pool-name)
      pool-vmImage:  $(pool-vmImage)
      project-to-publish: $(project-to-publish) # path to project that will be used in the publish tasks
      app-name: $(app-name) # application name will be used in docker repository url [app-bu].[app-project].[app-name]
      app-project: $(app-project) # application project will be used in docker repository url [app-bu].[app-project].[app-name]
      app-bu: $(app-bu) # application business unit will be used in docker repository url [app-bu].[app-project].[app-name]
      container-registry: "acrTanner"
      tests-enabled: false