//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsTipoCambio
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class InfoVariable : object
    {
        
        private System.Collections.Generic.List<WsTipoCambio.Variable> VariablesField;
        
        private System.Collections.Generic.List<WsTipoCambio.Var> CambioDiaField;
        
        private System.Collections.Generic.List<WsTipoCambio.VarDolar> CambioDolarField;
        
        private int TotalItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<WsTipoCambio.Variable> Variables
        {
            get
            {
                return this.VariablesField;
            }
            set
            {
                this.VariablesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.Generic.List<WsTipoCambio.Var> CambioDia
        {
            get
            {
                return this.CambioDiaField;
            }
            set
            {
                this.CambioDiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.Generic.List<WsTipoCambio.VarDolar> CambioDolar
        {
            get
            {
                return this.CambioDolarField;
            }
            set
            {
                this.CambioDolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalItems
        {
            get
            {
                return this.TotalItemsField;
            }
            set
            {
                this.TotalItemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Variable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class Variable : object
    {
        
        private int monedaField;
        
        private string descripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda
        {
            get
            {
                return this.monedaField;
            }
            set
            {
                this.monedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Var", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class Var : object
    {
        
        private int monedaField;
        
        private string fechaField;
        
        private float ventaField;
        
        private float compraField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda
        {
            get
            {
                return this.monedaField;
            }
            set
            {
                this.monedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float venta
        {
            get
            {
                return this.ventaField;
            }
            set
            {
                this.ventaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float compra
        {
            get
            {
                return this.compraField;
            }
            set
            {
                this.compraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VarDolar", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VarDolar : object
    {
        
        private string fechaField;
        
        private float referenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float referencia
        {
            get
            {
                return this.referenciaField;
            }
            set
            {
                this.referenciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class DataVariable : object
    {
        
        private System.Collections.Generic.List<WsTipoCambio.Var> VarsField;
        
        private int TotalItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<WsTipoCambio.Var> Vars
        {
            get
            {
                return this.VarsField;
            }
            set
            {
                this.VarsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TotalItems
        {
            get
            {
                return this.TotalItemsField;
            }
            set
            {
                this.TotalItemsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/", ConfigurationName="WsTipoCambio.TipoCambioSoap")]
    public interface TipoCambioSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VariablesDisponiblesResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/VariablesDisponibles", ReplyAction="*")]
        WsTipoCambio.VariablesDisponiblesResponse VariablesDisponibles(WsTipoCambio.VariablesDisponiblesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/VariablesDisponibles", ReplyAction="*")]
        System.Threading.Tasks.Task<WsTipoCambio.VariablesDisponiblesResponse> VariablesDisponiblesAsync(WsTipoCambio.VariablesDisponiblesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VariablesResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/Variables", ReplyAction="*")]
        WsTipoCambio.VariablesResponse Variables(WsTipoCambio.VariablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/Variables", ReplyAction="*")]
        System.Threading.Tasks.Task<WsTipoCambio.VariablesResponse> VariablesAsync(WsTipoCambio.VariablesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial", ReplyAction="*")]
        WsTipoCambio.TipoCambioFechaInicialResponse TipoCambioFechaInicial(WsTipoCambio.TipoCambioFechaInicialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial", ReplyAction="*")]
        System.Threading.Tasks.Task<WsTipoCambio.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(WsTipoCambio.TipoCambioFechaInicialRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRango", ReplyAction="*")]
        WsTipoCambio.TipoCambioRangoResponse TipoCambioRango(WsTipoCambio.TipoCambioRangoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRango", ReplyAction="*")]
        System.Threading.Tasks.Task<WsTipoCambio.TipoCambioRangoResponse> TipoCambioRangoAsync(WsTipoCambio.TipoCambioRangoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda", ReplyAction="*")]
        WsTipoCambio.TipoCambioFechaInicialMonedaResponse TipoCambioFechaInicialMoneda(WsTipoCambio.TipoCambioFechaInicialMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<WsTipoCambio.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(WsTipoCambio.TipoCambioFechaInicialMonedaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda", ReplyAction="*")]
        WsTipoCambio.TipoCambioRangoMonedaResponse TipoCambioRangoMoneda(WsTipoCambio.TipoCambioRangoMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<WsTipoCambio.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(WsTipoCambio.TipoCambioRangoMonedaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TipoCambioDiaResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDia", ReplyAction="*")]
        WsTipoCambio.TipoCambioDiaResponse TipoCambioDia(WsTipoCambio.TipoCambioDiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDia", ReplyAction="*")]
        System.Threading.Tasks.Task<WsTipoCambio.TipoCambioDiaResponse> TipoCambioDiaAsync(WsTipoCambio.TipoCambioDiaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TipoCambioDiaStringResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString", ReplyAction="*")]
        WsTipoCambio.TipoCambioDiaStringResponse TipoCambioDiaString(WsTipoCambio.TipoCambioDiaStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString", ReplyAction="*")]
        System.Threading.Tasks.Task<WsTipoCambio.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync(WsTipoCambio.TipoCambioDiaStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponibles", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public WsTipoCambio.VariablesDisponiblesRequestBody Body;
        
        public VariablesDisponiblesRequest()
        {
        }
        
        public VariablesDisponiblesRequest(WsTipoCambio.VariablesDisponiblesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class VariablesDisponiblesRequestBody
    {
        
        public VariablesDisponiblesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponiblesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public WsTipoCambio.VariablesDisponiblesResponseBody Body;
        
        public VariablesDisponiblesResponse()
        {
        }
        
        public VariablesDisponiblesResponse(WsTipoCambio.VariablesDisponiblesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesDisponiblesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WsTipoCambio.InfoVariable VariablesDisponiblesResult;
        
        public VariablesDisponiblesResponseBody()
        {
        }
        
        public VariablesDisponiblesResponseBody(WsTipoCambio.InfoVariable VariablesDisponiblesResult)
        {
            this.VariablesDisponiblesResult = VariablesDisponiblesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Variables", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public WsTipoCambio.VariablesRequestBody Body;
        
        public VariablesRequest()
        {
        }
        
        public VariablesRequest(WsTipoCambio.VariablesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int variable;
        
        public VariablesRequestBody()
        {
        }
        
        public VariablesRequestBody(int variable)
        {
            this.variable = variable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public WsTipoCambio.VariablesResponseBody Body;
        
        public VariablesResponse()
        {
        }
        
        public VariablesResponse(WsTipoCambio.VariablesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WsTipoCambio.InfoVariable VariablesResult;
        
        public VariablesResponseBody()
        {
        }
        
        public VariablesResponseBody(WsTipoCambio.InfoVariable VariablesResult)
        {
            this.VariablesResult = VariablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicial", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public WsTipoCambio.TipoCambioFechaInicialRequestBody Body;
        
        public TipoCambioFechaInicialRequest()
        {
        }
        
        public TipoCambioFechaInicialRequest(WsTipoCambio.TipoCambioFechaInicialRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        public TipoCambioFechaInicialRequestBody()
        {
        }
        
        public TipoCambioFechaInicialRequestBody(string fechainit)
        {
            this.fechainit = fechainit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public WsTipoCambio.TipoCambioFechaInicialResponseBody Body;
        
        public TipoCambioFechaInicialResponse()
        {
        }
        
        public TipoCambioFechaInicialResponse(WsTipoCambio.TipoCambioFechaInicialResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WsTipoCambio.DataVariable TipoCambioFechaInicialResult;
        
        public TipoCambioFechaInicialResponseBody()
        {
        }
        
        public TipoCambioFechaInicialResponseBody(WsTipoCambio.DataVariable TipoCambioFechaInicialResult)
        {
            this.TipoCambioFechaInicialResult = TipoCambioFechaInicialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRango", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public WsTipoCambio.TipoCambioRangoRequestBody Body;
        
        public TipoCambioRangoRequest()
        {
        }
        
        public TipoCambioRangoRequest(WsTipoCambio.TipoCambioRangoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        public TipoCambioRangoRequestBody()
        {
        }
        
        public TipoCambioRangoRequestBody(string fechainit, string fechafin)
        {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public WsTipoCambio.TipoCambioRangoResponseBody Body;
        
        public TipoCambioRangoResponse()
        {
        }
        
        public TipoCambioRangoResponse(WsTipoCambio.TipoCambioRangoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WsTipoCambio.DataVariable TipoCambioRangoResult;
        
        public TipoCambioRangoResponseBody()
        {
        }
        
        public TipoCambioRangoResponseBody(WsTipoCambio.DataVariable TipoCambioRangoResult)
        {
            this.TipoCambioRangoResult = TipoCambioRangoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public WsTipoCambio.TipoCambioFechaInicialMonedaRequestBody Body;
        
        public TipoCambioFechaInicialMonedaRequest()
        {
        }
        
        public TipoCambioFechaInicialMonedaRequest(WsTipoCambio.TipoCambioFechaInicialMonedaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int moneda;
        
        public TipoCambioFechaInicialMonedaRequestBody()
        {
        }
        
        public TipoCambioFechaInicialMonedaRequestBody(string fechainit, int moneda)
        {
            this.fechainit = fechainit;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public WsTipoCambio.TipoCambioFechaInicialMonedaResponseBody Body;
        
        public TipoCambioFechaInicialMonedaResponse()
        {
        }
        
        public TipoCambioFechaInicialMonedaResponse(WsTipoCambio.TipoCambioFechaInicialMonedaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WsTipoCambio.DataVariable TipoCambioFechaInicialMonedaResult;
        
        public TipoCambioFechaInicialMonedaResponseBody()
        {
        }
        
        public TipoCambioFechaInicialMonedaResponseBody(WsTipoCambio.DataVariable TipoCambioFechaInicialMonedaResult)
        {
            this.TipoCambioFechaInicialMonedaResult = TipoCambioFechaInicialMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public WsTipoCambio.TipoCambioRangoMonedaRequestBody Body;
        
        public TipoCambioRangoMonedaRequest()
        {
        }
        
        public TipoCambioRangoMonedaRequest(WsTipoCambio.TipoCambioRangoMonedaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int moneda;
        
        public TipoCambioRangoMonedaRequestBody()
        {
        }
        
        public TipoCambioRangoMonedaRequestBody(string fechainit, string fechafin, int moneda)
        {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public WsTipoCambio.TipoCambioRangoMonedaResponseBody Body;
        
        public TipoCambioRangoMonedaResponse()
        {
        }
        
        public TipoCambioRangoMonedaResponse(WsTipoCambio.TipoCambioRangoMonedaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WsTipoCambio.DataVariable TipoCambioRangoMonedaResult;
        
        public TipoCambioRangoMonedaResponseBody()
        {
        }
        
        public TipoCambioRangoMonedaResponseBody(WsTipoCambio.DataVariable TipoCambioRangoMonedaResult)
        {
            this.TipoCambioRangoMonedaResult = TipoCambioRangoMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDia", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public WsTipoCambio.TipoCambioDiaRequestBody Body;
        
        public TipoCambioDiaRequest()
        {
        }
        
        public TipoCambioDiaRequest(WsTipoCambio.TipoCambioDiaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaRequestBody
    {
        
        public TipoCambioDiaRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public WsTipoCambio.TipoCambioDiaResponseBody Body;
        
        public TipoCambioDiaResponse()
        {
        }
        
        public TipoCambioDiaResponse(WsTipoCambio.TipoCambioDiaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WsTipoCambio.InfoVariable TipoCambioDiaResult;
        
        public TipoCambioDiaResponseBody()
        {
        }
        
        public TipoCambioDiaResponseBody(WsTipoCambio.InfoVariable TipoCambioDiaResult)
        {
            this.TipoCambioDiaResult = TipoCambioDiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaString", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public WsTipoCambio.TipoCambioDiaStringRequestBody Body;
        
        public TipoCambioDiaStringRequest()
        {
        }
        
        public TipoCambioDiaStringRequest(WsTipoCambio.TipoCambioDiaStringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaStringRequestBody
    {
        
        public TipoCambioDiaStringRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaStringResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public WsTipoCambio.TipoCambioDiaStringResponseBody Body;
        
        public TipoCambioDiaStringResponse()
        {
        }
        
        public TipoCambioDiaStringResponse(WsTipoCambio.TipoCambioDiaStringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaStringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TipoCambioDiaStringResult;
        
        public TipoCambioDiaStringResponseBody()
        {
        }
        
        public TipoCambioDiaStringResponseBody(string TipoCambioDiaStringResult)
        {
            this.TipoCambioDiaStringResult = TipoCambioDiaStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface TipoCambioSoapChannel : WsTipoCambio.TipoCambioSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class TipoCambioSoapClient : System.ServiceModel.ClientBase<WsTipoCambio.TipoCambioSoap>, WsTipoCambio.TipoCambioSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TipoCambioSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TipoCambioSoapClient.GetBindingForEndpoint(endpointConfiguration), TipoCambioSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TipoCambioSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TipoCambioSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TipoCambioSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TipoCambioSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TipoCambioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsTipoCambio.VariablesDisponiblesResponse WsTipoCambio.TipoCambioSoap.VariablesDisponibles(WsTipoCambio.VariablesDisponiblesRequest request)
        {
            return base.Channel.VariablesDisponibles(request);
        }
        
        public WsTipoCambio.InfoVariable VariablesDisponibles()
        {
            WsTipoCambio.VariablesDisponiblesRequest inValue = new WsTipoCambio.VariablesDisponiblesRequest();
            inValue.Body = new WsTipoCambio.VariablesDisponiblesRequestBody();
            WsTipoCambio.VariablesDisponiblesResponse retVal = ((WsTipoCambio.TipoCambioSoap)(this)).VariablesDisponibles(inValue);
            return retVal.Body.VariablesDisponiblesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsTipoCambio.VariablesDisponiblesResponse> WsTipoCambio.TipoCambioSoap.VariablesDisponiblesAsync(WsTipoCambio.VariablesDisponiblesRequest request)
        {
            return base.Channel.VariablesDisponiblesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsTipoCambio.VariablesDisponiblesResponse> VariablesDisponiblesAsync()
        {
            WsTipoCambio.VariablesDisponiblesRequest inValue = new WsTipoCambio.VariablesDisponiblesRequest();
            inValue.Body = new WsTipoCambio.VariablesDisponiblesRequestBody();
            return ((WsTipoCambio.TipoCambioSoap)(this)).VariablesDisponiblesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsTipoCambio.VariablesResponse WsTipoCambio.TipoCambioSoap.Variables(WsTipoCambio.VariablesRequest request)
        {
            return base.Channel.Variables(request);
        }
        
        public WsTipoCambio.InfoVariable Variables(int variable)
        {
            WsTipoCambio.VariablesRequest inValue = new WsTipoCambio.VariablesRequest();
            inValue.Body = new WsTipoCambio.VariablesRequestBody();
            inValue.Body.variable = variable;
            WsTipoCambio.VariablesResponse retVal = ((WsTipoCambio.TipoCambioSoap)(this)).Variables(inValue);
            return retVal.Body.VariablesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsTipoCambio.VariablesResponse> WsTipoCambio.TipoCambioSoap.VariablesAsync(WsTipoCambio.VariablesRequest request)
        {
            return base.Channel.VariablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsTipoCambio.VariablesResponse> VariablesAsync(int variable)
        {
            WsTipoCambio.VariablesRequest inValue = new WsTipoCambio.VariablesRequest();
            inValue.Body = new WsTipoCambio.VariablesRequestBody();
            inValue.Body.variable = variable;
            return ((WsTipoCambio.TipoCambioSoap)(this)).VariablesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsTipoCambio.TipoCambioFechaInicialResponse WsTipoCambio.TipoCambioSoap.TipoCambioFechaInicial(WsTipoCambio.TipoCambioFechaInicialRequest request)
        {
            return base.Channel.TipoCambioFechaInicial(request);
        }
        
        public WsTipoCambio.DataVariable TipoCambioFechaInicial(string fechainit)
        {
            WsTipoCambio.TipoCambioFechaInicialRequest inValue = new WsTipoCambio.TipoCambioFechaInicialRequest();
            inValue.Body = new WsTipoCambio.TipoCambioFechaInicialRequestBody();
            inValue.Body.fechainit = fechainit;
            WsTipoCambio.TipoCambioFechaInicialResponse retVal = ((WsTipoCambio.TipoCambioSoap)(this)).TipoCambioFechaInicial(inValue);
            return retVal.Body.TipoCambioFechaInicialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsTipoCambio.TipoCambioFechaInicialResponse> WsTipoCambio.TipoCambioSoap.TipoCambioFechaInicialAsync(WsTipoCambio.TipoCambioFechaInicialRequest request)
        {
            return base.Channel.TipoCambioFechaInicialAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsTipoCambio.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(string fechainit)
        {
            WsTipoCambio.TipoCambioFechaInicialRequest inValue = new WsTipoCambio.TipoCambioFechaInicialRequest();
            inValue.Body = new WsTipoCambio.TipoCambioFechaInicialRequestBody();
            inValue.Body.fechainit = fechainit;
            return ((WsTipoCambio.TipoCambioSoap)(this)).TipoCambioFechaInicialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsTipoCambio.TipoCambioRangoResponse WsTipoCambio.TipoCambioSoap.TipoCambioRango(WsTipoCambio.TipoCambioRangoRequest request)
        {
            return base.Channel.TipoCambioRango(request);
        }
        
        public WsTipoCambio.DataVariable TipoCambioRango(string fechainit, string fechafin)
        {
            WsTipoCambio.TipoCambioRangoRequest inValue = new WsTipoCambio.TipoCambioRangoRequest();
            inValue.Body = new WsTipoCambio.TipoCambioRangoRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            WsTipoCambio.TipoCambioRangoResponse retVal = ((WsTipoCambio.TipoCambioSoap)(this)).TipoCambioRango(inValue);
            return retVal.Body.TipoCambioRangoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsTipoCambio.TipoCambioRangoResponse> WsTipoCambio.TipoCambioSoap.TipoCambioRangoAsync(WsTipoCambio.TipoCambioRangoRequest request)
        {
            return base.Channel.TipoCambioRangoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsTipoCambio.TipoCambioRangoResponse> TipoCambioRangoAsync(string fechainit, string fechafin)
        {
            WsTipoCambio.TipoCambioRangoRequest inValue = new WsTipoCambio.TipoCambioRangoRequest();
            inValue.Body = new WsTipoCambio.TipoCambioRangoRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            return ((WsTipoCambio.TipoCambioSoap)(this)).TipoCambioRangoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsTipoCambio.TipoCambioFechaInicialMonedaResponse WsTipoCambio.TipoCambioSoap.TipoCambioFechaInicialMoneda(WsTipoCambio.TipoCambioFechaInicialMonedaRequest request)
        {
            return base.Channel.TipoCambioFechaInicialMoneda(request);
        }
        
        public WsTipoCambio.DataVariable TipoCambioFechaInicialMoneda(string fechainit, int moneda)
        {
            WsTipoCambio.TipoCambioFechaInicialMonedaRequest inValue = new WsTipoCambio.TipoCambioFechaInicialMonedaRequest();
            inValue.Body = new WsTipoCambio.TipoCambioFechaInicialMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.moneda = moneda;
            WsTipoCambio.TipoCambioFechaInicialMonedaResponse retVal = ((WsTipoCambio.TipoCambioSoap)(this)).TipoCambioFechaInicialMoneda(inValue);
            return retVal.Body.TipoCambioFechaInicialMonedaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsTipoCambio.TipoCambioFechaInicialMonedaResponse> WsTipoCambio.TipoCambioSoap.TipoCambioFechaInicialMonedaAsync(WsTipoCambio.TipoCambioFechaInicialMonedaRequest request)
        {
            return base.Channel.TipoCambioFechaInicialMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsTipoCambio.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(string fechainit, int moneda)
        {
            WsTipoCambio.TipoCambioFechaInicialMonedaRequest inValue = new WsTipoCambio.TipoCambioFechaInicialMonedaRequest();
            inValue.Body = new WsTipoCambio.TipoCambioFechaInicialMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.moneda = moneda;
            return ((WsTipoCambio.TipoCambioSoap)(this)).TipoCambioFechaInicialMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsTipoCambio.TipoCambioRangoMonedaResponse WsTipoCambio.TipoCambioSoap.TipoCambioRangoMoneda(WsTipoCambio.TipoCambioRangoMonedaRequest request)
        {
            return base.Channel.TipoCambioRangoMoneda(request);
        }
        
        public WsTipoCambio.DataVariable TipoCambioRangoMoneda(string fechainit, string fechafin, int moneda)
        {
            WsTipoCambio.TipoCambioRangoMonedaRequest inValue = new WsTipoCambio.TipoCambioRangoMonedaRequest();
            inValue.Body = new WsTipoCambio.TipoCambioRangoMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            inValue.Body.moneda = moneda;
            WsTipoCambio.TipoCambioRangoMonedaResponse retVal = ((WsTipoCambio.TipoCambioSoap)(this)).TipoCambioRangoMoneda(inValue);
            return retVal.Body.TipoCambioRangoMonedaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsTipoCambio.TipoCambioRangoMonedaResponse> WsTipoCambio.TipoCambioSoap.TipoCambioRangoMonedaAsync(WsTipoCambio.TipoCambioRangoMonedaRequest request)
        {
            return base.Channel.TipoCambioRangoMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsTipoCambio.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(string fechainit, string fechafin, int moneda)
        {
            WsTipoCambio.TipoCambioRangoMonedaRequest inValue = new WsTipoCambio.TipoCambioRangoMonedaRequest();
            inValue.Body = new WsTipoCambio.TipoCambioRangoMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            inValue.Body.moneda = moneda;
            return ((WsTipoCambio.TipoCambioSoap)(this)).TipoCambioRangoMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsTipoCambio.TipoCambioDiaResponse WsTipoCambio.TipoCambioSoap.TipoCambioDia(WsTipoCambio.TipoCambioDiaRequest request)
        {
            return base.Channel.TipoCambioDia(request);
        }
        
        public WsTipoCambio.InfoVariable TipoCambioDia()
        {
            WsTipoCambio.TipoCambioDiaRequest inValue = new WsTipoCambio.TipoCambioDiaRequest();
            inValue.Body = new WsTipoCambio.TipoCambioDiaRequestBody();
            WsTipoCambio.TipoCambioDiaResponse retVal = ((WsTipoCambio.TipoCambioSoap)(this)).TipoCambioDia(inValue);
            return retVal.Body.TipoCambioDiaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsTipoCambio.TipoCambioDiaResponse> WsTipoCambio.TipoCambioSoap.TipoCambioDiaAsync(WsTipoCambio.TipoCambioDiaRequest request)
        {
            return base.Channel.TipoCambioDiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsTipoCambio.TipoCambioDiaResponse> TipoCambioDiaAsync()
        {
            WsTipoCambio.TipoCambioDiaRequest inValue = new WsTipoCambio.TipoCambioDiaRequest();
            inValue.Body = new WsTipoCambio.TipoCambioDiaRequestBody();
            return ((WsTipoCambio.TipoCambioSoap)(this)).TipoCambioDiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsTipoCambio.TipoCambioDiaStringResponse WsTipoCambio.TipoCambioSoap.TipoCambioDiaString(WsTipoCambio.TipoCambioDiaStringRequest request)
        {
            return base.Channel.TipoCambioDiaString(request);
        }
        
        public string TipoCambioDiaString()
        {
            WsTipoCambio.TipoCambioDiaStringRequest inValue = new WsTipoCambio.TipoCambioDiaStringRequest();
            inValue.Body = new WsTipoCambio.TipoCambioDiaStringRequestBody();
            WsTipoCambio.TipoCambioDiaStringResponse retVal = ((WsTipoCambio.TipoCambioSoap)(this)).TipoCambioDiaString(inValue);
            return retVal.Body.TipoCambioDiaStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsTipoCambio.TipoCambioDiaStringResponse> WsTipoCambio.TipoCambioSoap.TipoCambioDiaStringAsync(WsTipoCambio.TipoCambioDiaStringRequest request)
        {
            return base.Channel.TipoCambioDiaStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsTipoCambio.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync()
        {
            WsTipoCambio.TipoCambioDiaStringRequest inValue = new WsTipoCambio.TipoCambioDiaStringRequest();
            inValue.Body = new WsTipoCambio.TipoCambioDiaStringRequestBody();
            return ((WsTipoCambio.TipoCambioSoap)(this)).TipoCambioDiaStringAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TipoCambioSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TipoCambioSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TipoCambioSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.banguat.gob.gt/variables/ws/TipoCambio.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TipoCambioSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.banguat.gob.gt/variables/ws/TipoCambio.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TipoCambioSoap,
            
            TipoCambioSoap12,
        }
    }
}
